name: 'Theme Settings'
handle: theme_settings
description: 'Configure theme settings and global elements'
route: ''
template: ''
settings:
    seoable: 0
    creditable: 0
    navigatable: 1
    publishable: 0
    revisionable: 0
    categorizable: 0
types:
    settings:
        name: Settings
        description: 'Configure theme settings and global elements'
        route: ''
        template: ''
        fields:
            alert_banner:
                name: 'Alert Banner'
                type: wysiwyg
                group: 'Header & Footer'
                attributes:
                    readonly: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Display content in an alert banner that will show site-wide. Useful for promotions, emergency alerts, etc...'
                validation:
                    required: ''
            alert_banner_display:
                name: 'Alert Banner Display'
                type: select
                group: 'Header & Footer'
                attributes:
                    multiple: ''
                    readonly: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Choose the display status of the alert banner. Set to "None" to disable from view.'
                    class: ''
                    options:
                        -
                            checked: '1'
                            label: None
                            value: None
                        -
                            label: 'Top of page'
                            value: top
                        -
                            label: 'Bottom of page'
                            value: bottom
                validation:
                    required: required
            copyright:
                name: Copyright
                type: wysiwyg
                group: 'Header & Footer'
                attributes:
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: ''
                validation:
                    required: ''
            account_settings:
                name: 'Account Settings'
                type: content
                group: 'Social Media'
                attributes:
                    body: '<h2>Social Media Links</h2><br><p>Add links to your social media pages to display on your website. Please include ''https://'' at the beginning of the URL.</p>'
                validation:
                    required: ''
            social_media_display:
                name: 'Social Media Display'
                type: select
                group: 'Social Media'
                attributes:
                    multiple: ''
                    readonly: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Choose to enable or disable the display of social media links on your website.'
                    class: ''
                    options:
                        -
                            label: Enabled
                            value: 'true'
                            checked: '1'
                        -
                            label: Disabled
                            value: ''
                validation:
                    required: required
            facebook:
                name: Facebook
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to Facebook page'
                    class: ''
                validation:
                    required: ''
            instagram:
                name: Instagram
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to Instagram page'
                    class: ''
                validation:
                    required: ''
            twitter:
                name: Twitter
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to Twitter page'
                    class: ''
                validation:
                    required: ''
            pinterest:
                name: Pinterest
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to Pinterest page'
                    class: ''
                validation:
                    required: ''
            youtube:
                name: YouTube
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to YouTube page'
                    class: ''
                validation:
                    required: ''
            linkedin:
                name: LinkedIn
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Enter full URL to LinkedIn page'
                    class: ''
                validation:
                    required: ''
            advanced_settings:
                name: 'Advanced Settings'
                type: content
                group: 'Social Media'
                attributes:
                    body: '<hr><h2>Social Media Accounts & IDs</h2><br><p>Associate your social media accounts or publisher IDs with your website. All values below are optional.</p>'
                validation:
                    required: ''
            share_image:
                name: 'Share Image'
                type: assets
                group: 'Social Media'
                attributes:
                    mimetype:
                        - image
                    multiSelect: ''
                    help: 'Set an image to display if your website is shared on social media. Image should be a ratio of 1.91:1, at least 600x315 pixels but 1200x630 or larger is preferred (up to 5MB).'
                validation:
                    required: ''
            twitter_publisher:
                name: 'Twitter Publisher'
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Optional. Add a Twitter handle to associate with content on your website. Example: @username'
                    class: ''
                validation:
                    required: ''
            facebook_admin_id:
                name: 'Facebook Admin ID'
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Optional. May be required for Facebook page insights. You may enter multiple ID''s as a comma separated list. Example: 1234567, 89101112, 12141516'
                    class: ''
                validation:
                    required: ''
            facebook_app_id:
                name: 'Facebook App ID'
                type: input
                group: 'Social Media'
                attributes:
                    type: text
                    read_only: ''
                    disabled: ''
                    placeholder: ''
                    help: 'Optional. May be required for page insights or plugin integrations.'
                    class: ''
                validation:
                    required: ''